### ISSUE TITLE
Running times need to be decimal

### ISSUE THREAD

**Issue by PGrimes** [gman-wa/RWLL-Player-Evaluations#3]
Running times need to be decimal.

**Comment by gman-wa** [comment]
in chrome and ios i can enter a decimal in that field with the keyboard

**Comment by PGrimes** [comment]
When I press enter on Chrome it comes up with a warning asking to enter a valid value, helpfully letting me know the nearest valid value is 4 or 5 for 4.5.

**Comment by gman-wa** [comment]
input type=number allows for a 'step' attribute - which i have set to 0.1 for both baserunning and pitching velocity.  not sure if we need a float for pitching speed, and do we need hundredths for baserunning time?

**Comment by gman-wa** [comment]
also changed player id to just input type='text' - couldn't get number or tel to work properly and allow hyphens on the ios keyboard - could be we change our numbers from

2-234
to
2*234
or
2#234

then we could use type='tel' and get the nice big telephone keyboard

**Comment by PGrimes** [comment]
Your the registrar.  I think that 2#234 would be fine.  or we could just make them 4 digit numbers.  1XXX and 2XXX

**Comment by gman-wa** [comment]
i like four digit numbers.  and maybe people can just enter numbers and we don't have to re-print all those ...
