### ISSUE TITLE
non jquery cross-browser JS to ensure player id has a value?

### ISSUE THREAD

**Issue by gman-wa** [gman-wa/RWLL-Player-Evaluations#9]
hey paul, do you have any nice concise non-jquery JS to check for a value in a form field?

so far i've avoided loading jquery which would be my goto for this.

ios does not enforce the html 5 required attribute.

**Comment by PGrimes** [comment]
What do you want to validate?  ParseInt, ParseFloat are your friends.  
Example:
function validPlayerNum(number,failFun) {
  var num = parseInt(number);
  if !(num > 1000 && num < 3000)
 {
    failFun(num);
 };
}

Is that what your looking for?  You can call this onSubmit...

**Comment by gman-wa** [comment]
yeah - thats good, i'll incorporate this.

been so long since getElementbyID ...

**Comment by PGrimes** [comment]
Cleaner logic if (num < 1000 || num > 3000)

**Comment by PGrimes** [comment]
if (num > 1000 && num < 3000)  {console.log('Yay')} else {console.log('Boo')};

**Comment by gman-wa** [comment]
ok - this is implemented and pushed out - when this is tested i can put back the 'required' attributes and let browsers that can deal with it natively do just that.

**Comment by PGrimes** [comment]
I think we should validate the player id on registration, and then validate the player ID for the stations vs the known registered list, but that can come after the demo.

**Comment by gman-wa** [comment]
yeah, i'll do another round of validation in php on the process page and send back to the respective pages with error messages

**Comment by gman-wa** [comment]
using a poor mans non framework method to check for a player id.  JS tries to load the player image from S3 (calculated url) - if the player image is there, then assume registration record is there.  if not image load throws error we can catch and show error message.  we could toss all this and just use jquery 3 - just 30KB minified, and likely a users mobile browser already has this cached.  but right now, this app is JS framework-less
